"""add project table

Revision ID: 7d2e52671ffb
Revises: 
Create Date: 2026-02-28 19:28:55.960896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2e52671ffb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.create_index('idx_user_project', 'record', ['user_id', 'project_id'], unique=False)
    op.create_foreign_key(None, 'record', 'project', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_index('idx_user_project', table_name='record')
    op.drop_column('record', 'project_id')
    # ### end Alembic commands ###
